### ISSUE TITLE
[FEATURE REQUEST] Java Code Formatter

### ISSUE THREAD

**Issue by debasishbsws** [TheAlgorithms/Java#4224]
### What would you like to Propose?

The current Clang format linter definitely does its job to identify linting errors in the code.
But I think it will be better if we could have a formatter that we can integrate with CI jobs to auto-formate code if possible.
Therefore, It will be better to have a Java code formatter.

### Issue details

Currently, contributors have to format the code manually. though it can a auto fixable

**Comment by debasishbsws** [comment]
@siriak what is your thought on this?

**Comment by siriak** [comment]
I think it's a great idea. Having a formatter is better than only having a check.

**Comment by acbin** [comment]
Great idea. The [clang-format-lint-action](https://github.com/DoozyX/clang-format-lint-action) support format the code inplace

```yml
name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: '.'
        exclude: './lib'
        extensions: 'h,cpp,c'
        clangFormatVersion: 16
        inplace: True
    - uses: EndBug/add-and-commit@v9
      with:
        author_name: Clang Robot
        author_email: robot@example.com
        message: 'Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
